# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0005_auto_20180820_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=10)),
                ('home_result', models.IntegerField()),
                ('away_result', models.IntegerField()),
                ('date', models.DateField()),
                ('finished', models.BooleanField(default=True)),
                ('matchday', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='Home.Team')),
                ('channels', models.ManyToManyField(to='Home.Channel')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='Home.Team')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Stadium')),
            ],
        ),
    ]
