# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0002_auto_20180821_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament_round',
            field=models.CharField(default='', max_length=10),
        ),
    ]
