# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Matches', '0006_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=180, null=True)),
                ('date', models.DateField()),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Matches.Match')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
