# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0007_auto_20180822_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
