# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0008_auto_20180822_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
