# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fifacode', models.CharField(max_length=30)),
                ('iso2', models.CharField(max_length=30)),
                ('flag', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
