# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20180819_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
