# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_channel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
