# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
